// <auto-generated />
using LibrosAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibrosAPI.Migrations
{
    [DbContext(typeof(LibrosDbContext))]
    partial class LibrosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibrosAPI.Models.Libro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnioPublicacion")
                        .HasColumnType("int");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Libros");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnioPublicacion = 1967,
                            Autor = "Gabriel García Márquez",
                            Titulo = "Cien años de soledad"
                        },
                        new
                        {
                            Id = 2,
                            AnioPublicacion = 1605,
                            Autor = "Miguel de Cervantes",
                            Titulo = "Don Quijote de la Mancha"
                        },
                        new
                        {
                            Id = 3,
                            AnioPublicacion = 1985,
                            Autor = "Gabriel García Márquez",
                            Titulo = "El amor en los tiempos del cólera"
                        },
                        new
                        {
                            Id = 4,
                            AnioPublicacion = 1944,
                            Autor = "Jorge Luis Borges",
                            Titulo = "Ficciones"
                        },
                        new
                        {
                            Id = 5,
                            AnioPublicacion = 1949,
                            Autor = "Jorge Luis Borges",
                            Titulo = "El Aleph"
                        },
                        new
                        {
                            Id = 6,
                            AnioPublicacion = 1963,
                            Autor = "Julio Cortázar",
                            Titulo = "Rayuela"
                        },
                        new
                        {
                            Id = 7,
                            AnioPublicacion = 1963,
                            Autor = "Mario Vargas Llosa",
                            Titulo = "La ciudad y los perros"
                        },
                        new
                        {
                            Id = 8,
                            AnioPublicacion = 1969,
                            Autor = "Mario Vargas Llosa",
                            Titulo = "Conversación en La Catedral"
                        },
                        new
                        {
                            Id = 9,
                            AnioPublicacion = 2000,
                            Autor = "Mario Vargas Llosa",
                            Titulo = "La fiesta del chivo"
                        },
                        new
                        {
                            Id = 10,
                            AnioPublicacion = 1955,
                            Autor = "Juan Rulfo",
                            Titulo = "Pedro Páramo"
                        },
                        new
                        {
                            Id = 11,
                            AnioPublicacion = 1953,
                            Autor = "Juan Rulfo",
                            Titulo = "El llano en llamas"
                        },
                        new
                        {
                            Id = 12,
                            AnioPublicacion = 1960,
                            Autor = "Mario Benedetti",
                            Titulo = "La tregua"
                        },
                        new
                        {
                            Id = 13,
                            AnioPublicacion = 1965,
                            Autor = "Mario Benedetti",
                            Titulo = "Gracias por el fuego"
                        },
                        new
                        {
                            Id = 14,
                            AnioPublicacion = 1982,
                            Autor = "Isabel Allende",
                            Titulo = "La casa de los espíritus"
                        },
                        new
                        {
                            Id = 15,
                            AnioPublicacion = 1984,
                            Autor = "Isabel Allende",
                            Titulo = "De amor y de sombra"
                        },
                        new
                        {
                            Id = 16,
                            AnioPublicacion = 1987,
                            Autor = "Isabel Allende",
                            Titulo = "Eva Luna"
                        },
                        new
                        {
                            Id = 17,
                            AnioPublicacion = 1981,
                            Autor = "Gabriel García Márquez",
                            Titulo = "Crónica de una muerte anunciada"
                        },
                        new
                        {
                            Id = 18,
                            AnioPublicacion = 1961,
                            Autor = "Gabriel García Márquez",
                            Titulo = "El coronel no tiene quien le escriba"
                        },
                        new
                        {
                            Id = 19,
                            AnioPublicacion = 1953,
                            Autor = "Alejo Carpentier",
                            Titulo = "Los pasos perdidos"
                        },
                        new
                        {
                            Id = 20,
                            AnioPublicacion = 1949,
                            Autor = "Alejo Carpentier",
                            Titulo = "El reino de este mundo"
                        },
                        new
                        {
                            Id = 21,
                            AnioPublicacion = 1934,
                            Autor = "Jorge Icaza",
                            Titulo = "Huasipungo"
                        },
                        new
                        {
                            Id = 22,
                            AnioPublicacion = 1929,
                            Autor = "Rómulo Gallegos",
                            Titulo = "Doña Bárbara"
                        },
                        new
                        {
                            Id = 23,
                            AnioPublicacion = 1924,
                            Autor = "José Eustasio Rivera",
                            Titulo = "La vorágine"
                        },
                        new
                        {
                            Id = 24,
                            AnioPublicacion = 1946,
                            Autor = "Miguel Ángel Asturias",
                            Titulo = "Señor Presidente"
                        },
                        new
                        {
                            Id = 25,
                            AnioPublicacion = 1949,
                            Autor = "Miguel Ángel Asturias",
                            Titulo = "Hombres de maíz"
                        },
                        new
                        {
                            Id = 26,
                            AnioPublicacion = 1961,
                            Autor = "Ernesto Sabato",
                            Titulo = "Sobre héroes y tumbas"
                        },
                        new
                        {
                            Id = 27,
                            AnioPublicacion = 1948,
                            Autor = "Ernesto Sabato",
                            Titulo = "El túnel"
                        },
                        new
                        {
                            Id = 28,
                            AnioPublicacion = 1974,
                            Autor = "Ernesto Sabato",
                            Titulo = "Abaddón el exterminador"
                        },
                        new
                        {
                            Id = 29,
                            AnioPublicacion = 1998,
                            Autor = "Roberto Bolaño",
                            Titulo = "Los detectives salvajes"
                        },
                        new
                        {
                            Id = 30,
                            AnioPublicacion = 2004,
                            Autor = "Roberto Bolaño",
                            Titulo = "2666"
                        },
                        new
                        {
                            Id = 31,
                            AnioPublicacion = 1996,
                            Autor = "Roberto Bolaño",
                            Titulo = "Estrella distante"
                        },
                        new
                        {
                            Id = 32,
                            AnioPublicacion = 1962,
                            Autor = "Carlos Fuentes",
                            Titulo = "La muerte de Artemio Cruz"
                        },
                        new
                        {
                            Id = 33,
                            AnioPublicacion = 1962,
                            Autor = "Carlos Fuentes",
                            Titulo = "Aura"
                        },
                        new
                        {
                            Id = 34,
                            AnioPublicacion = 1975,
                            Autor = "Carlos Fuentes",
                            Titulo = "Terra Nostra"
                        },
                        new
                        {
                            Id = 35,
                            AnioPublicacion = 1966,
                            Autor = "José Lezama Lima",
                            Titulo = "Paradiso"
                        },
                        new
                        {
                            Id = 36,
                            AnioPublicacion = 1974,
                            Autor = "Augusto Roa Bastos",
                            Titulo = "Yo el Supremo"
                        },
                        new
                        {
                            Id = 37,
                            AnioPublicacion = 1960,
                            Autor = "Augusto Roa Bastos",
                            Titulo = "Hijo de hombre"
                        },
                        new
                        {
                            Id = 38,
                            AnioPublicacion = 2001,
                            Autor = "Carlos Ruiz Zafón",
                            Titulo = "La sombra del viento"
                        },
                        new
                        {
                            Id = 39,
                            AnioPublicacion = 2008,
                            Autor = "Carlos Ruiz Zafón",
                            Titulo = "El juego del ángel"
                        },
                        new
                        {
                            Id = 40,
                            AnioPublicacion = 2011,
                            Autor = "Carlos Ruiz Zafón",
                            Titulo = "El prisionero del cielo"
                        },
                        new
                        {
                            Id = 41,
                            AnioPublicacion = 2016,
                            Autor = "Carlos Ruiz Zafón",
                            Titulo = "El laberinto de los espíritus"
                        },
                        new
                        {
                            Id = 42,
                            AnioPublicacion = 1999,
                            Autor = "Carlos Ruiz Zafón",
                            Titulo = "Marina"
                        },
                        new
                        {
                            Id = 43,
                            AnioPublicacion = 2016,
                            Autor = "Fernando Aramburu",
                            Titulo = "Patria"
                        },
                        new
                        {
                            Id = 44,
                            AnioPublicacion = 1980,
                            Autor = "Umberto Eco",
                            Titulo = "El nombre de la rosa"
                        },
                        new
                        {
                            Id = 45,
                            AnioPublicacion = 1988,
                            Autor = "Umberto Eco",
                            Titulo = "El péndulo de Foucault"
                        },
                        new
                        {
                            Id = 46,
                            AnioPublicacion = 1949,
                            Autor = "George Orwell",
                            Titulo = "1984"
                        },
                        new
                        {
                            Id = 47,
                            AnioPublicacion = 1945,
                            Autor = "George Orwell",
                            Titulo = "Rebelión en la granja"
                        },
                        new
                        {
                            Id = 48,
                            AnioPublicacion = 1932,
                            Autor = "Aldous Huxley",
                            Titulo = "Un mundo feliz"
                        },
                        new
                        {
                            Id = 49,
                            AnioPublicacion = 1953,
                            Autor = "Ray Bradbury",
                            Titulo = "Fahrenheit 451"
                        },
                        new
                        {
                            Id = 50,
                            AnioPublicacion = 1950,
                            Autor = "Ray Bradbury",
                            Titulo = "Crónicas marcianas"
                        },
                        new
                        {
                            Id = 51,
                            AnioPublicacion = 1954,
                            Autor = "J.R.R. Tolkien",
                            Titulo = "El señor de los anillos: La comunidad del anillo"
                        },
                        new
                        {
                            Id = 52,
                            AnioPublicacion = 1954,
                            Autor = "J.R.R. Tolkien",
                            Titulo = "El señor de los anillos: Las dos torres"
                        },
                        new
                        {
                            Id = 53,
                            AnioPublicacion = 1955,
                            Autor = "J.R.R. Tolkien",
                            Titulo = "El señor de los anillos: El retorno del rey"
                        },
                        new
                        {
                            Id = 54,
                            AnioPublicacion = 1937,
                            Autor = "J.R.R. Tolkien",
                            Titulo = "El Hobbit"
                        },
                        new
                        {
                            Id = 55,
                            AnioPublicacion = 1977,
                            Autor = "J.R.R. Tolkien",
                            Titulo = "El Silmarillion"
                        },
                        new
                        {
                            Id = 56,
                            AnioPublicacion = 1866,
                            Autor = "Fiódor Dostoyevski",
                            Titulo = "Crimen y castigo"
                        },
                        new
                        {
                            Id = 57,
                            AnioPublicacion = 1880,
                            Autor = "Fiódor Dostoyevski",
                            Titulo = "Los hermanos Karamázov"
                        },
                        new
                        {
                            Id = 58,
                            AnioPublicacion = 1869,
                            Autor = "Fiódor Dostoyevski",
                            Titulo = "El idiota"
                        },
                        new
                        {
                            Id = 59,
                            AnioPublicacion = 1869,
                            Autor = "León Tolstói",
                            Titulo = "Guerra y paz"
                        },
                        new
                        {
                            Id = 60,
                            AnioPublicacion = 1877,
                            Autor = "León Tolstói",
                            Titulo = "Anna Karénina"
                        },
                        new
                        {
                            Id = 61,
                            AnioPublicacion = 1813,
                            Autor = "Jane Austen",
                            Titulo = "Orgullo y prejuicio"
                        },
                        new
                        {
                            Id = 62,
                            AnioPublicacion = 1811,
                            Autor = "Jane Austen",
                            Titulo = "Sensatez y sentimientos"
                        },
                        new
                        {
                            Id = 63,
                            AnioPublicacion = 1815,
                            Autor = "Jane Austen",
                            Titulo = "Emma"
                        },
                        new
                        {
                            Id = 64,
                            AnioPublicacion = 1847,
                            Autor = "Emily Brontë",
                            Titulo = "Cumbres Borrascosas"
                        },
                        new
                        {
                            Id = 65,
                            AnioPublicacion = 1847,
                            Autor = "Charlotte Brontë",
                            Titulo = "Jane Eyre"
                        },
                        new
                        {
                            Id = 66,
                            AnioPublicacion = 1861,
                            Autor = "Charles Dickens",
                            Titulo = "Grandes esperanzas"
                        },
                        new
                        {
                            Id = 67,
                            AnioPublicacion = 1859,
                            Autor = "Charles Dickens",
                            Titulo = "Historia de dos ciudades"
                        },
                        new
                        {
                            Id = 68,
                            AnioPublicacion = 1838,
                            Autor = "Charles Dickens",
                            Titulo = "Oliver Twist"
                        },
                        new
                        {
                            Id = 69,
                            AnioPublicacion = 1851,
                            Autor = "Herman Melville",
                            Titulo = "Moby Dick"
                        },
                        new
                        {
                            Id = 70,
                            AnioPublicacion = 1925,
                            Autor = "F. Scott Fitzgerald",
                            Titulo = "El gran Gatsby"
                        },
                        new
                        {
                            Id = 71,
                            AnioPublicacion = 1952,
                            Autor = "Ernest Hemingway",
                            Titulo = "El viejo y el mar"
                        },
                        new
                        {
                            Id = 72,
                            AnioPublicacion = 1940,
                            Autor = "Ernest Hemingway",
                            Titulo = "Por quién doblan las campanas"
                        },
                        new
                        {
                            Id = 73,
                            AnioPublicacion = 1926,
                            Autor = "Ernest Hemingway",
                            Titulo = "Fiesta"
                        },
                        new
                        {
                            Id = 74,
                            AnioPublicacion = 1952,
                            Autor = "John Steinbeck",
                            Titulo = "Al este del Edén"
                        },
                        new
                        {
                            Id = 75,
                            AnioPublicacion = 1939,
                            Autor = "John Steinbeck",
                            Titulo = "Las uvas de la ira"
                        },
                        new
                        {
                            Id = 76,
                            AnioPublicacion = 1937,
                            Autor = "John Steinbeck",
                            Titulo = "De ratones y hombres"
                        },
                        new
                        {
                            Id = 77,
                            AnioPublicacion = 1951,
                            Autor = "J.D. Salinger",
                            Titulo = "El guardián entre el centeno"
                        },
                        new
                        {
                            Id = 78,
                            AnioPublicacion = 1960,
                            Autor = "Harper Lee",
                            Titulo = "Matar a un ruiseñor"
                        },
                        new
                        {
                            Id = 79,
                            AnioPublicacion = 1913,
                            Autor = "Marcel Proust",
                            Titulo = "En busca del tiempo perdido"
                        },
                        new
                        {
                            Id = 80,
                            AnioPublicacion = 1942,
                            Autor = "Albert Camus",
                            Titulo = "El extranjero"
                        },
                        new
                        {
                            Id = 81,
                            AnioPublicacion = 1947,
                            Autor = "Albert Camus",
                            Titulo = "La peste"
                        },
                        new
                        {
                            Id = 82,
                            AnioPublicacion = 1942,
                            Autor = "Albert Camus",
                            Titulo = "El mito de Sísifo"
                        },
                        new
                        {
                            Id = 83,
                            AnioPublicacion = 1915,
                            Autor = "Franz Kafka",
                            Titulo = "La metamorfosis"
                        },
                        new
                        {
                            Id = 84,
                            AnioPublicacion = 1925,
                            Autor = "Franz Kafka",
                            Titulo = "El proceso"
                        },
                        new
                        {
                            Id = 85,
                            AnioPublicacion = 1926,
                            Autor = "Franz Kafka",
                            Titulo = "El castillo"
                        },
                        new
                        {
                            Id = 86,
                            AnioPublicacion = 1922,
                            Autor = "James Joyce",
                            Titulo = "Ulises"
                        },
                        new
                        {
                            Id = 87,
                            AnioPublicacion = 1916,
                            Autor = "James Joyce",
                            Titulo = "Retrato del artista adolescente"
                        },
                        new
                        {
                            Id = 88,
                            AnioPublicacion = 1914,
                            Autor = "James Joyce",
                            Titulo = "Dublineses"
                        },
                        new
                        {
                            Id = 89,
                            AnioPublicacion = 1890,
                            Autor = "Oscar Wilde",
                            Titulo = "El retrato de Dorian Gray"
                        },
                        new
                        {
                            Id = 90,
                            AnioPublicacion = 1897,
                            Autor = "Bram Stoker",
                            Titulo = "Drácula"
                        },
                        new
                        {
                            Id = 91,
                            AnioPublicacion = 1818,
                            Autor = "Mary Shelley",
                            Titulo = "Frankenstein"
                        },
                        new
                        {
                            Id = 92,
                            AnioPublicacion = 1862,
                            Autor = "Victor Hugo",
                            Titulo = "Los miserables"
                        },
                        new
                        {
                            Id = 93,
                            AnioPublicacion = 1831,
                            Autor = "Victor Hugo",
                            Titulo = "Nuestra Señora de París"
                        },
                        new
                        {
                            Id = 94,
                            AnioPublicacion = 1844,
                            Autor = "Alexandre Dumas",
                            Titulo = "El conde de Montecristo"
                        },
                        new
                        {
                            Id = 95,
                            AnioPublicacion = 1844,
                            Autor = "Alexandre Dumas",
                            Titulo = "Los tres mosqueteros"
                        },
                        new
                        {
                            Id = 96,
                            AnioPublicacion = 1857,
                            Autor = "Gustave Flaubert",
                            Titulo = "Madame Bovary"
                        },
                        new
                        {
                            Id = 97,
                            AnioPublicacion = 1320,
                            Autor = "Dante Alighieri",
                            Titulo = "La divina comedia"
                        },
                        new
                        {
                            Id = 98,
                            AnioPublicacion = 1943,
                            Autor = "Antoine de Saint-Exupéry",
                            Titulo = "El principito"
                        },
                        new
                        {
                            Id = 99,
                            AnioPublicacion = 1995,
                            Autor = "José Saramago",
                            Titulo = "Ensayo sobre la ceguera"
                        },
                        new
                        {
                            Id = 100,
                            AnioPublicacion = 1991,
                            Autor = "José Saramago",
                            Titulo = "El evangelio según Jesucristo"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
